[package]
name = "cfdyndns"
version = "0.0.3"
authors = ["Cole Mickens <cole.mickens@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
pretty_env_logger = "0.4.0"
reqwest = { version = "0.10.4", features = ["blocking", "json"] }
serde = "1.0.104"
serde_json = "1.0.48"
trust-dns-client = "0.19.3"
